apiVersion: v1
kind: Service
metadata:
  name: previsao-tempo-amazonia-api-service
spec:
  type: NodePort
  selector:
    app: previsao-tempo-amazonia-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
